apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: my-node-app
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: my-node-app
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/npike-vmware/my-node-app.git
